# Generated by Andrew Heebum Kwak (kh-1143@hanmail.net)

{
    'includes':
    [
        '../BuildAll.gypi',
    ],

    'targets':
    [
        {
            'target_name': 'test',
            'type': 'executable',
            
            'dependencies':
            [
                '../LogTracer/LogTracer.gyp:*',
            ],

            'defines':
            [

            ],
            
            'include_dirs':
            [
                '../include',
            ],

            'sources':
            [
                './main.cpp',
            ],
            
            'conditions':
            [
                [
                    'OS=="linux"',
                    {
                        'library_dirs':
                        [

                        ],
                    },
                ],
            ],
        },
    ],
}
