# Generated by Andrew Heebum Kwak (kh-1143@hanmail.net)

{
    'includes':
    [
        './BuildAll.gypi',
    ],

	# 프로젝트 생성
	'targets':
	[
	    {
	        'target_name': 'BuildAll',
	        'type': 'none',
	        'dependencies':
	        [
                './LogTracer/LogTracer.gyp:*',
                './test/test.gyp:*',
	        ],
        },
	],
}
