#!/bin/bash

rm -rf "out"
rm -rf "clean"
rm -rf "Makefile"
rm -rf "BuildAll.xcodeproj"
rm -rf "gyp-mac-tool"
rm -rf "BuildAll.Makefile"
rm -rf "BuildAll.target.mk"
rm -rf "test/test.xcodeproj"
rm -rf "test/test.Makefile"
rm -rf "test/test.target.mk"
rm -rf "LogTracer/LogTracer.xcodeproj"
rm -rf "LogTracer/LogTracer.Makefile"
rm -rf "LogTracer/LogTracer.target.mk"
