# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := test
### Rules for final target.
LDFLAGS_Debug := \
	-g \
	-O0

LDFLAGS_Release := \
	-g \
	-O0

LIBS :=

$(obj).target/src/libtest.a: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/src/libtest.a: LIBS := $(LIBS)
$(obj).target/src/libtest.a: TOOLSET := $(TOOLSET)
$(obj).target/src/libtest.a:  FORCE_DO_CMD
	$(call do_cmd,alink_thin)

all_deps += $(obj).target/src/libtest.a
# Add target alias
.PHONY: test
test: $(obj).target/src/libtest.a

# Add target alias to "all" target.
.PHONY: all
all: test

